In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('/workspaces/Daily-Practice/Day 12 - Pandas/employee.csv')
display(df)

      Name   Department  Salary  Experience
0    Alice  Engineering    7500           3
1      Bob    Marketing    6500           5
2  Charlie  Engineering    8000           7
3    Diana           HR    6000           2
4      Eve    Marketing    7000           4

### EDA (Exploratory Data Analysis) with Pandas

- first step in data analysis and ML too
- three parts:
    1. Data Cleaning - identify and remove missing values, or outliers etc
    2. Data Summarization - check the dataset characteristics and descriptive statistics
    3. Data Visualization - visualize complex data into visuals for easy interpretation

- one of the main job responsibilities of a Data Analyst

- some methods that we can run on dataframes
- Basic Inspection methods: (Data Summarization)
    - `df.head()` - gives first 5 elements
        - an argument of 10 gives first 10 elements
    - df.tail() - last 5 but argument can change it
    - `df.sample()` - one random entry from dataset
        - argument can change that too
        - used to check how datasets look like inside
- Basic attributes of a dataframe:
    - `df.shape`
    - df.size
    - df.ndim
    - `df.dtypes`

- Methods for Statistical information as well
    - `df.info()` - general info about df
        - how many records, columns, data type of columns
        - also gives an idea if there are any missing values in data
    - `df.describe()` - gives statistical measurements of columns like count, mean, min, max, std, percentiles
-

In [8]:
display(df.head(3))
display(df.tail(3))
display(df.sample(2))
df.dtypes

      Name   Department  Salary  Experience
0    Alice  Engineering    7500           3
1      Bob    Marketing    6500           5
2  Charlie  Engineering    8000           7

      Name   Department  Salary  Experience
2  Charlie  Engineering    8000           7
3    Diana           HR    6000           2
4      Eve    Marketing    7000           4

      Name   Department  Salary  Experience
2  Charlie  Engineering    8000           7
0    Alice  Engineering    7500           3

Name            str
Department      str
Salary        int64
Experience    int64
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Department  5 non-null      str
 2   Salary      5 non-null      int64
 3   Experience  5 non-null      int64
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [10]:
df.describe()

            Salary  Experience
count     5.000000    5.000000
mean   7000.000000    4.200000
std     790.569415    1.923538
min    6000.000000    2.000000
25%    6500.000000    3.000000
50%    7000.000000    4.000000
75%    7500.000000    5.000000
max    8000.000000    7.000000

Exercise
- download: https://www.kaggle.com/datasets/juhibhojani/house-price
- perform the operations especially EDA learnt in today's class on it

In [11]:
import pandas as pd

df = pd.read_csv('wc_2026_fixtures.csv')
df.head()

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
4,A,Group Stage,Czechia,Mexico,Estadio Azteca,Mexico City,Mexico,2026-06-24,21:00 ET,UEFA,41.0,Ivan Hasek,CONCACAF,15.0,Javier Aguirre

In [12]:
df.sample(5)

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
2,A,Group Stage,South Korea,Mexico,Estadio Akron,Guadalajara,Mexico,2026-06-18,21:00 ET,AFC,25.0,Hong Myung-bo,CONCACAF,15.0,Javier Aguirre
36,G,Group Stage,Belgium,Egypt,Lumen Field,Seattle,USA,2026-06-15,15:00 ET,UEFA,9.0,Domenico Tedesco,CAF,29.0,Hossam El-Badry
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
25,E,Group Stage,Ivory Coast,Ecuador,Lincoln Financial Field,Philadelphia,USA,2026-06-14,19:00 ET,CAF,33.0,Emerse Faé,CONMEBOL,24.0,Sebastián Beccacece
92,NaN,Round of 16,R32 W9,R32 W10,SoFi Stadium,Inglewood,USA,2026-07-06,TBD,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.dtypes

group                      str
stage                      str
team1                      str
team2                      str
venue                      str
city                       str
country                    str
date                       str
kickoff_et                 str
team1_confederation        str
team1_fifa_rank        float64
team1_coach                str
team2_confederation        str
team2_fifa_rank        float64
team2_coach                str
dtype: object

- object is used for mixed data types
    - same as numpy array if you mixed data types
    -

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   group                72 non-null     str
 1   stage                104 non-null    str
 2   team1                104 non-null    str
 3   team2                104 non-null    str
 4   venue                104 non-null    str
 5   city                 104 non-null    str
 6   country              104 non-null    str
 7   date                 104 non-null    str
 8   kickoff_et           104 non-null    str
 9   team1_confederation  72 non-null     str
 10  team1_fifa_rank      72 non-null     float64
 11  team1_coach          72 non-null     str
 12  team2_confederation  72 non-null     str
 13  team2_fifa_rank      72 non-null     float64
 14  team2_coach          72 non-null     str
dtypes: float64(2), str(13)
memory usage: 12.3 KB

## Filtering
- filter rows and columns
- uses boolean indexing
- keep only the rows you care about
- 
- df[condition] # or mask

In [15]:
# show matches played in Canada
df[df['country'] == 'Canada']

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
8,B,Group Stage,Switzerland,Bosnia and Herzegovina,BC Place,Vancouver,Canada,2026-06-18,15:00 ET,UEFA,19.0,Murat Yakin,UEFA,52.0,Sergej Barbarez
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
10,B,Group Stage,Switzerland,Canada,BC Place,Vancouver,Canada,2026-06-24,18:00 ET,UEFA,19.0,Murat Yakin,CONCACAF,30.0,Jesse Marsch
11,B,Group Stage,Bosnia and Herzegovina,Qatar,BMO Field,Toronto,Canada,2026-06-24,18:00 ET,UEFA,52.0,Sergej Barbarez,AFC,35.0,Marquez Lopez
67,L,Group Stage,Ghana,Panama,BMO Field,Toronto,Canada,2026-06-17,18:00 ET,CAF,65.0,Otto Addo,CONCACAF,53.0,Thomas Christiansen
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen
83,NaN,Round of 32,1L,2K,BC Place,Vancouver,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,Round of 32,Best 3rd #1,Best 3rd #2,BMO Field,Toronto,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# data for matches in which team1_fifa_rank was <= 10
df[df['team1_fifa_rank'] <= 10]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
12,C,Group Stage,Brazil,Morocco,MetLife Stadium,East Rutherford,USA,2026-06-13,18:00 ET,CONMEBOL,6.0,Dorival Júnior,CAF,8.0,Walid Regragui
14,C,Group Stage,Brazil,Scotland,MetLife Stadium,East Rutherford,USA,2026-06-19,21:00 ET,CONMEBOL,6.0,Dorival Júnior,UEFA,47.0,Steve Clarke
15,C,Group Stage,Morocco,Haiti,MetLife Stadium,East Rutherford,USA,2026-06-19,21:00 ET,CAF,8.0,Walid Regragui,CONCACAF,83.0,Marc Collat
17,C,Group Stage,Morocco,Haiti,Gillette Stadium,Foxborough,USA,2026-06-24,21:00 ET,CAF,8.0,Walid Regragui,CONCACAF,83.0,Marc Collat
24,E,Group Stage,Germany,Curaçao,NRG Stadium,Houston,USA,2026-06-14,13:00 ET,UEFA,10.0,Julian Nagelsmann,CONCACAF,81.0,Dick Advocaat
26,E,Group Stage,Germany,Ivory Coast,NRG Stadium,Houston,USA,2026-06-20,19:00 ET,UEFA,10.0,Julian Nagelsmann,CAF,33.0,Emerse Faé
30,F,Group Stage,Netherlands,Japan,AT&T Stadium,Arlington,USA,2026-06-14,16:00 ET,UEFA,7.0,Ronald Koeman,AFC,18.0,Hajime Moriyasu
32,F,Group Stage,Netherlands,Sweden,NRG Stadium,Houston,USA,2026-06-20,19:00 ET,UEFA,7.0,Ronald Koeman,UEFA,39.0,Jon Dahl Tomasson
36,G,Group Stage,Belgium,Egypt,Lumen Field,Seattle,USA,2026-06-15,15:00 ET,UEFA,9.0,Domenico Tedesco,CAF,29.0,Hossam El-Badry
38,G,Group Stage,Belgium,Iran,SoFi Stadium,Inglewood,USA,2026-06-21,18:00 ET,UEFA,9.0,Domenico Tedesco,AFC,21.0,Amir Ghalenoei
42,H,Group Stage,Spain,Cape Verde,Mercedes-Benz Stadium,Atlanta,USA,2026-06-15,12:00 ET,UEFA,2.0,Luis de la Fuente,CAF,70.0,Pedro Brito
44,H,Group Stage,Spain,Saudi Arabia,Estadio Akron,Guadalajara,Mexico,2026-06-21,21:00 ET,UEFA,2.0,Luis de la Fuente,AFC,57.0,Roberto Mancini
48,I,Group Stage,France,Senegal,MetLife Stadium,East Rutherford,USA,2026-06-16,15:00 ET,UEFA,1.0,Didier Deschamps,CAF,14.0,Aliou Cissé
50,I,Group Stage,France,Iraq,Lincoln Financial Field,Philadelphia,USA,2026-06-22,17:00 ET,UEFA,1.0,Didier Deschamps,AFC,61.0,Graham Arnold
54,J,Group Stage,Argentina,Algeria,Arrowhead Stadium,Kansas City,USA,2026-06-16,21:00 ET,CONMEBOL,3.0,Lionel Scaloni,CAF,36.0,Vladimir Petkovic
56,J,Group Stage,Argentina,Austria,AT&T Stadium,Arlington,USA,2026-06-22,13:00 ET,CONMEBOL,3.0,Lionel Scaloni,UEFA,23.0,Ralf Rangnick
60,K,Group Stage,Portugal,DR Congo,NRG Stadium,Houston,USA,2026-06-17,13:00 ET,UEFA,5.0,Roberto Martínez,CAF,51.0,Sébastien Desabre
62,K,Group Stage,Portugal,Uzbekistan,Arrowhead Stadium,Kansas City,USA,2026-06-23,13:00 ET,UEFA,5.0,Roberto Martínez,AFC,62.0,Srecko Katanec
66,L,Group Stage,England,Croatia,AT&T Stadium,Arlington,USA,2026-06-17,15:00 ET,UEFA,4.0,Thomas Tuchel,UEFA,11.0,Zlatko Dalić
68,L,Group Stage,England,Ghana,Gillette Stadium,Foxborough,USA,2026-06-23,19:00 ET,UEFA,4.0,Thomas Tuchel,CAF,65.0,Otto Addo

In [17]:
# data for matches in which both teams were < 10 fifa rank
df[(df['team1_fifa_rank']<10) & (df['team2_fifa_rank']<10)]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
12,C,Group Stage,Brazil,Morocco,MetLife Stadium,East Rutherford,USA,2026-06-13,18:00 ET,CONMEBOL,6.0,Dorival Júnior,CAF,8.0,Walid Regragui

In [18]:
# all matches where Mexico is playing,
# as team1, AND the venue is 'Estadio Azteca'
df[(df['team1'] == 'Mexico') & (df['venue'] == 'Estadio Azteca')]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos

In [19]:
# all matches played in either 'Toronto' OR 'Vancouver'
df[(df['city'] == 'Toronto')|(df['city'] == 'Vancouver')]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
8,B,Group Stage,Switzerland,Bosnia and Herzegovina,BC Place,Vancouver,Canada,2026-06-18,15:00 ET,UEFA,19.0,Murat Yakin,UEFA,52.0,Sergej Barbarez
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
10,B,Group Stage,Switzerland,Canada,BC Place,Vancouver,Canada,2026-06-24,18:00 ET,UEFA,19.0,Murat Yakin,CONCACAF,30.0,Jesse Marsch
11,B,Group Stage,Bosnia and Herzegovina,Qatar,BMO Field,Toronto,Canada,2026-06-24,18:00 ET,UEFA,52.0,Sergej Barbarez,AFC,35.0,Marquez Lopez
67,L,Group Stage,Ghana,Panama,BMO Field,Toronto,Canada,2026-06-17,18:00 ET,CAF,65.0,Otto Addo,CONCACAF,53.0,Thomas Christiansen
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen
83,NaN,Round of 32,1L,2K,BC Place,Vancouver,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,Round of 32,Best 3rd #1,Best 3rd #2,BMO Field,Toronto,Canada,2026-07-03,TBD,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# matches where:
# team1 ranked strictly better (lower number) than team2 AND
# match is either in Mexico OR Canada
df[(df['team1_fifa_rank'] < df['team2_fifa_rank']) & ((df['country'] == 'Mexico') | (df['country'] == 'Canada'))]

,group,stage,team1,team2,venue,city,country,date,kickoff_et,team1_confederation,team1_fifa_rank,team1_coach,team2_confederation,team2_fifa_rank,team2_coach
0,A,Group Stage,Mexico,South Africa,Estadio Azteca,Mexico City,Mexico,2026-06-11,20:00 ET,CONCACAF,15.0,Javier Aguirre,CAF,60.0,Hugo Broos
1,A,Group Stage,South Korea,Czechia,Estadio Akron,Guadalajara,Mexico,2026-06-11,22:00 ET,AFC,25.0,Hong Myung-bo,UEFA,41.0,Ivan Hasek
3,A,Group Stage,Czechia,South Africa,Estadio Akron,Guadalajara,Mexico,2026-06-18,18:00 ET,UEFA,41.0,Ivan Hasek,CAF,60.0,Hugo Broos
6,B,Group Stage,Canada,Bosnia and Herzegovina,BMO Field,Toronto,Canada,2026-06-12,15:00 ET,CONCACAF,30.0,Jesse Marsch,UEFA,52.0,Sergej Barbarez
8,B,Group Stage,Switzerland,Bosnia and Herzegovina,BC Place,Vancouver,Canada,2026-06-18,15:00 ET,UEFA,19.0,Murat Yakin,UEFA,52.0,Sergej Barbarez
9,B,Group Stage,Canada,Qatar,BC Place,Vancouver,Canada,2026-06-19,18:00 ET,CONCACAF,30.0,Jesse Marsch,AFC,35.0,Marquez Lopez
10,B,Group Stage,Switzerland,Canada,BC Place,Vancouver,Canada,2026-06-24,18:00 ET,UEFA,19.0,Murat Yakin,CONCACAF,30.0,Jesse Marsch
31,F,Group Stage,Sweden,Tunisia,Estadio BBVA,Monterrey,Mexico,2026-06-14,20:00 ET,UEFA,39.0,Jon Dahl Tomasson,CAF,40.0,Faouzi Benzarti
44,H,Group Stage,Spain,Saudi Arabia,Estadio Akron,Guadalajara,Mexico,2026-06-21,21:00 ET,UEFA,2.0,Luis de la Fuente,AFC,57.0,Roberto Mancini
69,L,Group Stage,Croatia,Panama,BMO Field,Toronto,Canada,2026-06-23,21:00 ET,UEFA,11.0,Zlatko Dalić,CONCACAF,53.0,Thomas Christiansen

In [21]:
mask = (df['team1_fifa_rank'] < df['team2_fifa_rank']) & ((df['country'] == 'Mexico') | (df['country'] == 'Canada'))
mask

0       True
1       True
2      False
3       True
4      False
       ...
99     False
100    False
101    False
102    False
103    False
Length: 104, dtype: bool

In [22]:
df2 = df.loc[mask, ['team1', 'team2', 'country']]
df2

          team1                   team2 country
0        Mexico            South Africa  Mexico
1   South Korea                 Czechia  Mexico
3       Czechia            South Africa  Mexico
6        Canada  Bosnia and Herzegovina  Canada
8   Switzerland  Bosnia and Herzegovina  Canada
9        Canada                   Qatar  Canada
10  Switzerland                  Canada  Canada
31       Sweden                 Tunisia  Mexico
44        Spain            Saudi Arabia  Mexico
69      Croatia                  Panama  Canada

### Sorting Data in DFs
- highest numbers, or alphabetical order
- 
- df.sort_values(by= 'column') - will sort based on column values
- df.sort_index() - will sort rows based on index
- pass an argument `ascending = False` for descending order

In [23]:
df3 = df2.sort_values(by= 'team1', ascending= False)
df3

          team1                   team2 country
8   Switzerland  Bosnia and Herzegovina  Canada
10  Switzerland                  Canada  Canada
31       Sweden                 Tunisia  Mexico
44        Spain            Saudi Arabia  Mexico
1   South Korea                 Czechia  Mexico
0        Mexico            South Africa  Mexico
3       Czechia            South Africa  Mexico
69      Croatia                  Panama  Canada
6        Canada  Bosnia and Herzegovina  Canada
9        Canada                   Qatar  Canada

In [24]:
df3.sort_index()

          team1                   team2 country
0        Mexico            South Africa  Mexico
1   South Korea                 Czechia  Mexico
3       Czechia            South Africa  Mexico
6        Canada  Bosnia and Herzegovina  Canada
8   Switzerland  Bosnia and Herzegovina  Canada
9        Canada                   Qatar  Canada
10  Switzerland                  Canada  Canada
31       Sweden                 Tunisia  Mexico
44        Spain            Saudi Arabia  Mexico
69      Croatia                  Panama  Canada

In [36]:
df3.drop('country', axis= 1)

          team1                   team2
8   Switzerland  Bosnia and Herzegovina
10  Switzerland                  Canada
31       Sweden                 Tunisia
44        Spain            Saudi Arabia
1   South Korea                 Czechia
0        Mexico            South Africa
3       Czechia            South Africa
69      Croatia                  Panama
6        Canada  Bosnia and Herzegovina
9        Canada                   Qatar

## Aggregation
- Sometimes we need to get aggregate values of columns
- method: sum(), min(), max(), mean()
- 
- AXIS --- 0 >>>>> Operating column wise
- AXIS --- 1 >>>>> of rows

Use of axis argument 3 places:
- `Aggregate` --- Numpy 2D array --- DataFrame
    - axis = 0 ---> Column wise aggregates
    - axis = 1 ---> Row wise aggregates
- `Drop` a column or row in dataframes
    - axis = 0 ---> # Drop ROW
    - axis = 1 ---> # Drop COLUMN

- `Series.agg`(['mean', 'max', 'min', 'count', 'sum', 'std', 'var', 'prod'])

In [28]:
print(df.team1_fifa_rank.max())
df.team1_fifa_rank.min()

95.0

np.float64(1.0)

In [33]:
print(df[['team1_fifa_rank', 'team2_fifa_rank']].min())
print(df[['team1_fifa_rank', 'team2_fifa_rank']].max())
print(df[['team1_fifa_rank', 'team2_fifa_rank']].mean())
print(df[['team1_fifa_rank', 'team2_fifa_rank']].median())
df[['team1_fifa_rank', 'team2_fifa_rank']].mode().iloc[0]

team1_fifa_rank    1.0
team2_fifa_rank    1.0
dtype: float64
team1_fifa_rank    95.0
team2_fifa_rank    95.0
dtype: float64
team1_fifa_rank    30.208333
team2_fifa_rank    37.916667
dtype: float64
team1_fifa_rank    24.0
team2_fifa_rank    35.5
dtype: float64

team1_fifa_rank     1.0
team2_fifa_rank    14.0
Name: 0, dtype: float64

In [34]:
df[['team1_fifa_rank', 'team2_fifa_rank']].mean(axis= 1)

0      37.5
1      33.0
2      20.0
3      50.5
4      28.0
       ...
99      NaN
100     NaN
101     NaN
102     NaN
103     NaN
Length: 104, dtype: float64

In [41]:
df['team2_fifa_rank'].agg(['mean', 'min', 'max'])

mean    37.916667
min      1.000000
max     95.000000
Name: team2_fifa_rank, dtype: float64

In [ ]:
# drop all rows with missing values
df.dropna(inplace= True) # Original effected
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   group                72 non-null     str
 1   stage                72 non-null     str
 2   team1                72 non-null     str
 3   team2                72 non-null     str
 4   venue                72 non-null     str
 5   city                 72 non-null     str
 6   country              72 non-null     str
 7   date                 72 non-null     str
 8   kickoff_et           72 non-null     str
 9   team1_confederation  72 non-null     str
 10  team1_fifa_rank      72 non-null     float64
 11  team1_coach          72 non-null     str
 12  team2_confederation  72 non-null     str
 13  team2_fifa_rank      72 non-null     float64
 14  team2_coach          72 non-null     str
dtypes: float64(2), str(13)
memory usage: 8.6 KB
None

In [30]:
cond = (df['team1_fifa_rank']<=5) | (df['team2_fifa_rank']<=5)
df.loc[cond, ['team1', 'team2', 'team1_fifa_rank', 'team2_fifa_rank']]

        team1         team2  team1_fifa_rank  team2_fifa_rank
42      Spain    Cape Verde              2.0             70.0
44      Spain  Saudi Arabia              2.0             57.0
47    Uruguay         Spain             17.0              2.0
48     France       Senegal              1.0             14.0
50     France          Iraq              1.0             61.0
52     Norway        France             44.0              1.0
54  Argentina       Algeria              3.0             36.0
56  Argentina       Austria              3.0             23.0
59     Jordan     Argentina             68.0              3.0
60   Portugal      DR Congo              5.0             51.0
62   Portugal    Uzbekistan              5.0             62.0
64   Colombia      Portugal             13.0              5.0
66    England       Croatia              4.0             11.0
68    England         Ghana              4.0             65.0
70     Panama       England             53.0              4.0

## Grouping
- group the data by some category
- `df.groupby('Category')[['col1', 'col2', 'col3', ...]].aggregation()`
- 
- using df.group('category').count() - gives all columns for each row
- using df.group('category').size() - gives only categories and count
-

In [43]:
df_emp = pd.read_csv('/workspaces/Daily-Practice/Day 12 - Pandas/employee.csv')
df_emp

      Name   Department  Salary  Experience
0    Alice  Engineering    7500           3
1      Bob    Marketing    6500           5
2  Charlie  Engineering    8000           7
3    Diana           HR    6000           2
4      Eve    Marketing    7000           4

In [45]:
df_emp.groupby('Department')[['Salary', 'Experience']].count()

             Salary  Experience
Department
Engineering       2           2
HR                1           1
Marketing         2           2

In [46]:
df_emp.groupby('Department')[['Salary', 'Experience']].min()

             Salary  Experience
Department
Engineering    7500           3
HR             6000           2
Marketing      6500           4

In [47]:
df_emp.groupby('Department')[['Salary', 'Experience']].mean()

             Salary  Experience
Department
Engineering  7750.0         5.0
HR           6000.0         2.0
Marketing    6750.0         4.5

In [48]:
df.groupby('country')['date'].count()

country
Canada     7
Mexico    12
USA       53
Name: date, dtype: int64

In [49]:
df.groupby('country').size()

country
Canada     7
Mexico    12
USA       53
dtype: int64

#### Combine DataFrames
- two dataframe and you want to combine them together
-

JOINS - 
- are used to combine two tables
- this happens along a KEY column ---> PRIMARY KEY --- we cover this in SQL
- 
- https://tse4.mm.bing.net/th/id/OIP.lRkZ1jamrvFYbSdGu3nF5gAAAA?w=350&h=350&rs=1&pid=ImgDetMain&o=7&rm=3

In [52]:
stu = {
    'StudentID': [101, 102, 103],
    'Name': ['Aman', 'Sara', 'Johan']
}
df_stu = pd.DataFrame(stu)
display(df_stu)

marks = {
    'StudentID': [102, 103, 104],
    'Math': [85, 90, 78],
    'English': [88, 92, 80]
}
df_marks = pd.DataFrame(marks)
display(df_marks)

   StudentID   Name
0        101   Aman
1        102   Sara
2        103  Johan

   StudentID  Math  English
0        102    85       88
1        103    90       92
2        104    78       80

In [53]:
df_merged = pd.merge(df_stu, df_marks, on= 'StudentID', how= 'inner')
df_merged

   StudentID   Name  Math  English
0        102   Sara    85       88
1        103  Johan    90       92

In [54]:
df_lefted = pd.merge(df_stu, df_marks, on= 'StudentID', how= 'left')
df_lefted

   StudentID   Name  Math  English
0        101   Aman   NaN      NaN
1        102   Sara  85.0     88.0
2        103  Johan  90.0     92.0

In [55]:
df_righted = pd.merge(df_stu, df_marks, on= 'StudentID', how= 'right')
df_righted

   StudentID   Name  Math  English
0        102   Sara    85       88
1        103  Johan    90       92
2        104    NaN    78       80

In [57]:
df_full = pd.merge(df_stu, df_marks, on= 'StudentID', how= 'outer')
df_full

   StudentID   Name  Math  English
0        101   Aman   NaN      NaN
1        102   Sara  85.0     88.0
2        103  Johan  90.0     92.0
3        104    NaN  78.0     80.0

In [59]:
pd.concat([df_stu, df_marks], ignore_index= True)

   StudentID   Name  Math  English
0        101   Aman   NaN      NaN
1        102   Sara   NaN      NaN
2        103  Johan   NaN      NaN
3        102    NaN  85.0     88.0
4        103    NaN  90.0     92.0
5        104    NaN  78.0     80.0

---------

- Most companies still have databases that store data in Relational Databases
- using SQL is traditionally efficient, fast and what everybody
- SQL is good for querrying a database
    - get data from database
- 
- Pandas is based on python - has a lot of library support
    - easier to do ML with
    - analysis and visualise easily
    - has support for huge data
    - 
    - libraries like pySpark or Apache Spark --- tool used for big data analysis
    - 
    -