## Apriori
- algorithm will help you recommend the next item
-

In [ ]:
pip install mlxtend

In [1]:
import pandas as pd 
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
transaction = [
    ['Milk', 'Butter', 'Bread'],
    ['Milk', 'Bread'],
    ['Bread', 'Butter', 'Eggs'],
    ['Milk', 'Eggs'],
    ['Bread', 'Butter', 'Juice']
]

te = TransactionEncoder()

te_array = te.fit_transform(transaction)
te_array = te.fit(transaction).transform(transaction)

te_array

array([[ True,  True, False, False,  True],
       [ True, False, False, False,  True],
       [ True,  True,  True, False, False],
       [False, False,  True, False,  True],
       [ True,  True, False,  True, False]])

In [3]:
te.columns_

['Bread', 'Butter', 'Eggs', 'Juice', 'Milk']

In [4]:
df_transaction = pd.DataFrame(te_array, columns= te.columns_)
df_transaction

   Bread  Butter   Eggs  Juice   Milk
0   True    True  False  False   True
1   True   False  False  False   True
2   True    True   True  False  False
3  False   False   True  False   True
4   True    True  False   True  False

In [6]:
frequent_itemsets = apriori(df_transaction,
                            min_support= 0.4,
                            use_colnames= True)
frequent_itemsets

   support                    itemsets
0      0.8          frozenset({Bread})
1      0.6         frozenset({Butter})
2      0.4           frozenset({Eggs})
3      0.6           frozenset({Milk})
4      0.6  frozenset({Bread, Butter})
5      0.4    frozenset({Milk, Bread})

- Support: How often the rule appears in the dataset.
- Confidence: Probability of buying item B if item A is bought.
- Lift: Strength of the rule over random chance. (>1 means it's a good rule)

In [7]:
rules = association_rules(frequent_itemsets,
                          metric= 'confidence',
                          min_threshold= 0.7
                          )
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Bread}),frozenset({Butter}),0.8,0.6,0.6,0.75,1.25,1.0,0.12,1.6,1.0,0.75,0.375,0.875
1,frozenset({Butter}),frozenset({Bread}),0.6,0.8,0.6,1.00,1.25,1.0,0.12,inf,0.5,0.75,1.000,0.875

In [8]:
final_table = rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]
final_table

           antecedents          consequents  support  confidence  lift
0   frozenset({Bread})  frozenset({Butter})      0.6        0.75  1.25
1  frozenset({Butter})   frozenset({Bread})      0.6        1.00  1.25

In [12]:
current_cart = {'Bread'}
recommendation = final_table[rules['antecedents'] == current_cart]

recommendation

          antecedents          consequents  support  confidence  lift
0  frozenset({Bread})  frozenset({Butter})      0.6        0.75  1.25