# Pandas
- python library
- fast, powerful, flexible and easy to use open source data **analysis** and **manipulation** tool
- provides Series and Dataframe objects
- These objects are used to store and manipulate structured data (data in tabular form)
- 
- pandas comes from `Panel Data`
- `Python for Data Analysis`
- `s` refers to the series object

In [21]:
import pandas as pd

### Core Objects
- Series - is a one dimensional labelled array (like a single column)
    - series = one column
- DataFrame - a two-dimensional table made of multiple series of same index
    - dataFrame = a sheet of columns and rows

In [22]:
maths = pd.Series([20, 30, 40], dtype= 'int8', name= 'math')
print(maths)
type(maths)

0    20
1    30
2    40
Name: math, dtype: int8

pandas.Series

In [23]:
eng = pd.Series([20, 30, 40], name= 'english')
py = pd.Series([20, 55, 40], name= 'python')
sc = pd.Series([20, 99, 40], name= 'science')

In [24]:
pd.concat([maths, eng, py, sc])

0    20
1    30
2    40
0    20
1    30
2    40
0    20
1    55
2    40
0    20
1    99
2    40
dtype: int64

In [25]:
df = pd.concat([maths, eng, py, sc], axis= 1)
print(type(df))
df

<class 'pandas.DataFrame'>

   math  english  python  science
0    20       20      20       20
1    30       30      55       99
2    40       40      40       40

DataFrame - 
- column, rows
-

In [26]:
# dataframe from dictionary of lists --- each list has to be of same size
data = {
    'students': ['Alya', 'Hanna', 'Areeqa'],
    'Maths': [90, 85, 95],
    'English': [80, 75, 85]
}
df = pd.DataFrame(data)
print(df)
display(df)

  students  Maths  English
0     Alya     90       80
1    Hanna     85       75
2   Areeqa     95       85

  students  Maths  English
0     Alya     90       80
1    Hanna     85       75
2   Areeqa     95       85

In [27]:
# dataframe from list of dictionaries --- each dictionary can be of different size
# we can miss elements --- those elements will appear as NaN values
data = [
    {'Name': 'Alya', 'Age': 21, 'City': 'Alor Gajah'},
    {'Name': 'Hanna', 'City': 'Cheras'},
    {'Name': 'Areeqa', 'Age': 20}
]
df = pd.DataFrame(data)
df

     Name   Age        City
0    Alya  21.0  Alor Gajah
1   Hanna   NaN      Cheras
2  Areeqa  20.0         NaN

- NaN values
    - Not a Number
    - aka Missing Values

In [28]:
# dataframe from 2D arrays
data = [
    ['Alya', 21, 'Alor Gajah'],
    ['Hanna', 'Cheras'],
    ['Areeqa', 20]
]
df = pd.DataFrame(data)
df

        0       1           2
0    Alya      21  Alor Gajah
1   Hanna  Cheras         NaN
2  Areeqa      20         NaN

In [29]:
data = [
    ['Alya', 21, 'Alor Gajah'],
    ['Hanna', 22, 'Cheras'],
    ['Areeqa', 20]
]
df = pd.DataFrame(data, columns= ['Name', 'Age', 'City'])
df

     Name  Age        City
0    Alya   21  Alor Gajah
1   Hanna   22      Cheras
2  Areeqa   20         NaN

In [30]:
# DataFrames from Files

# csv file
df_csv = pd.read_csv('my_data.csv')

# Excel file
df_excel = pd.read_excel('my_data.xlsx')

# JSON file / API response
df_json = pd.read_json('my_data.json')

FileNotFoundError: [Errno 2] No such file or directory: 'my_data.csv'

Series has:
- Index
- Name

DataFrame will have:
- Header - is the names of columns
    - `pd`.`DataFrame`(file, `columns` = ['col1', 'col2', 'col3'])
- Index - 
    - `pd`.`DataFrame`(file, `columns` = ['col1', 'col2', 'col3'], `index` = [1, 2, 3])
    - index_col = 'column name' ===> argument we can pass as well
    - df.set_index('column name')

#### Mini-Activity

> 1. Create a `pd.Series` with 5 temperature values and print it.

> 2. Create a pd.DataFrame with columns '`City`' and '`Temperature`' for 3 cities.

> 3. Check the `type()` of each object you created.

> 4. Add a name to your Series and print it again.

In [ ]:
# 1
np.random.seed(42)
temp = np.random.randint(0, 40, 5)
t = pd.Series(temp)
print(t)

# 2
data = {
    'City': ['Dubai', 'Gaza', 'Putrajaya'],
    'Temp': [38, 32, 29]
}
df = pd.DataFrame(data)
display(df)

# 3
print(type(t))
print(type(df))

# 4
print(pd.Series(temp, name= 'Temperature'))

0    38
1    28
2    14
3     7
4    20
dtype: int64

        City  Temp
0      Dubai    38
1       Gaza    32
2  Putrajaya    29

<class 'pandas.Series'>
<class 'pandas.DataFrame'>
0    38
1    28
2    14
3     7
4    20
Name: Temperature, dtype: int64

### Reading from and writing to a CSV files
- pd.read_csv()

In [32]:
sample_data = """Name,Department,Salary,Experience
Alice, Engineering, 7500, 3
Bob, Marketing, 6500, 5
Charlie, Engineering, 8000, 7
Diana, HR, 6000, 2
Eve, Marketing, 7000, 4"""

with open('employee.csv', 'w') as f:
    f.write(sample_data)

In [ ]:
df = pd.read_csv('employee.csv')
df

      Name    Department   Salary   Experience
0    Alice   Engineering     7500            3
1      Bob     Marketing     6500            5
2  Charlie   Engineering     8000            7
3    Diana            HR     6000            2
4      Eve     Marketing     7000            4

In [ ]:
import numpy as np
results = np.random.randint(0, 101, (10, 3))
df_results = pd.DataFrame(results, columns= ['Maths', 'English', 'Science'])
display(df_results)

   Maths  English  Science
0     82       86       74
1     74       87       99
2     23        2       21
3     52        1       87
4     29       37        1
5     63       59       20
6     32       75       57
7     21       88       48
8     90       58       41
9     91       59       79

In [ ]:
df_results.to_csv('student_marks.csv', index= False)
df_results

   Maths  English  Science
0     82       86       74
1     74       87       99
2     23        2       21
3     52        1       87
4     29       37        1
5     63       59       20
6     32       75       57
7     21       88       48
8     90       58       41
9     91       59       79