## Working with DataFrames
-

In [82]:
import pandas as pd

In [83]:
df = pd.read_csv('employee.csv')
display(df)

      Name    Department  Salary  Experience
0    Alice   Engineering    7500           3
1      Bob     Marketing    6500           5
2  Charlie   Engineering    8000           7
3    Diana            HR    6000           2
4      Eve     Marketing    7000           4

## Column Selection in Pandas
- df['column_name']
- df.Column_name
- a single column will exist as a series object
- 
- df[data] - this indexing method will take a single argument --- a `string` or a `list`
    - what if we need multiple columns
    -

In [84]:
df['Name']

0      Alice
1        Bob
2    Charlie
3      Diana
4        Eve
Name: Name, dtype: str

In [85]:
df.Name

0      Alice
1        Bob
2    Charlie
3      Diana
4        Eve
Name: Name, dtype: str

In [86]:
columns = ["Name","Salary","Experience"]
df[columns]

      Name  Salary  Experience
0    Alice    7500           3
1      Bob    6500           5
2  Charlie    8000           7
3    Diana    6000           2
4      Eve    7000           4

In [87]:
df[['Name', 'Salary']]

      Name  Salary
0    Alice    7500
1      Bob    6500
2  Charlie    8000
3    Diana    6000
4      Eve    7000

# Selection using the Location or Labels
##### integer Location --- **.iloc[]**
- `df.iloc[row index]` # access rows
- 
- `df.iloc[row_index_slice]` # [start: end: stepsize]
- INDEXING ----
- `df.iloc[row_slice, column_slice]`

In [ ]:
df.iloc[0]

Name                 Alice
Department     Engineering
Salary                7500
Experience               3
Name: 0, dtype: object

In [89]:
df.iloc[0:1]

    Name    Department  Salary  Experience
0  Alice   Engineering    7500           3

In [90]:
df.iloc[0:5:2]

      Name    Department  Salary  Experience
0    Alice   Engineering    7500           3
2  Charlie   Engineering    8000           7
4      Eve     Marketing    7000           4

In [91]:
df.iloc[::-1]

      Name    Department  Salary  Experience
4      Eve     Marketing    7000           4
3    Diana            HR    6000           2
2  Charlie   Engineering    8000           7
1      Bob     Marketing    6500           5
0    Alice   Engineering    7500           3

In [92]:
df.iloc[1:4, 1]

1       Marketing
2     Engineering
3              HR
Name: Department, dtype: str

In [93]:
df.iloc[1:3, 1:3]

     Department  Salary
1     Marketing    6500
2   Engineering    8000

In [94]:
# last 2 entries for department and experience
df.iloc[-2:, [1, 3]]

   Department  Experience
3          HR           2
4   Marketing           4

##### Label - .loc[]
- focuses on labels
- df.loc[0:3] # targets the name of these rows
- Which are the indexes
-

In [95]:
df.loc[0]

Name                 Alice
Department     Engineering
Salary                7500
Experience               3
Name: 0, dtype: object

In [96]:
df.loc[:2]

      Name    Department  Salary  Experience
0    Alice   Engineering    7500           3
1      Bob     Marketing    6500           5
2  Charlie   Engineering    8000           7

In [97]:
df.loc[:2, ['Name','Experience']]

      Name  Experience
0    Alice           3
1      Bob           5
2  Charlie           7

In [98]:
df = pd.read_csv('employee.csv', index_col= 'Name')
df

           Department  Salary  Experience
Name
Alice     Engineering    7500           3
Bob         Marketing    6500           5
Charlie   Engineering    8000           7
Diana              HR    6000           2
Eve         Marketing    7000           4

In [99]:
ind = ['a', 'b', 'c', 'd', 'e']
df = pd.read_csv('employee.csv')
df['index'] = ind
display(df)

      Name    Department  Salary  Experience index
0    Alice   Engineering    7500           3     a
1      Bob     Marketing    6500           5     b
2  Charlie   Engineering    8000           7     c
3    Diana            HR    6000           2     d
4      Eve     Marketing    7000           4     e

In [100]:
df = df.set_index('index')
df

          Name    Department  Salary  Experience
index
a        Alice   Engineering    7500           3
b          Bob     Marketing    6500           5
c      Charlie   Engineering    8000           7
d        Diana            HR    6000           2
e          Eve     Marketing    7000           4

In [101]:
df.loc['a':'c', 'Name':'Experience':2]

          Name  Salary
index
a        Alice    7500
b          Bob    6500
c      Charlie    8000

In [102]:
df = pd.read_csv('employee.csv')
df.index = ('a', 'b', 'c', 'd', 'e')
df

      Name    Department  Salary  Experience
a    Alice   Engineering    7500           3
b      Bob     Marketing    6500           5
c  Charlie   Engineering    8000           7
d    Diana            HR    6000           2
e      Eve     Marketing    7000           4

In [103]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [104]:
df.columns

Index(['Name', 'Department', 'Salary', 'Experience'], dtype='str')

### Adding and Modifying Columns
-

In [105]:
df['email'] = ['alice@mail.com', 'bob@mail.com', 'char_lie@mail.com', 'd_Diana@mail.com', 'eve_01@mail.com']
df

      Name    Department  Salary  Experience              email
a    Alice   Engineering    7500           3     alice@mail.com
b      Bob     Marketing    6500           5       bob@mail.com
c  Charlie   Engineering    8000           7  char_lie@mail.com
d    Diana            HR    6000           2   d_Diana@mail.com
e      Eve     Marketing    7000           4    eve_01@mail.com

In [106]:
df['Department'] = [' Engineering', ' Marketing', ' Analytics', ' HR', ' Marketing']
df

      Name    Department  Salary  Experience              email
a    Alice   Engineering    7500           3     alice@mail.com
b      Bob     Marketing    6500           5       bob@mail.com
c  Charlie     Analytics    8000           7  char_lie@mail.com
d    Diana            HR    6000           2   d_Diana@mail.com
e      Eve     Marketing    7000           4    eve_01@mail.com

In [107]:
df.Salary = df.Salary*10 # Scaling operation
df

      Name    Department  Salary  Experience              email
a    Alice   Engineering   75000           3     alice@mail.com
b      Bob     Marketing   65000           5       bob@mail.com
c  Charlie     Analytics   80000           7  char_lie@mail.com
d    Diana            HR   60000           2   d_Diana@mail.com
e      Eve     Marketing   70000           4    eve_01@mail.com

In [108]:
df.loc['d', 'email'] = 'itsdiana@gmail.com'
df.iloc[1, 1] = 'IT'
df

      Name    Department  Salary  Experience               email
a    Alice   Engineering   75000           3      alice@mail.com
b      Bob            IT   65000           5        bob@mail.com
c  Charlie     Analytics   80000           7   char_lie@mail.com
d    Diana            HR   60000           2  itsdiana@gmail.com
e      Eve     Marketing   70000           4     eve_01@mail.com