# Data Cleaning

- First you check for inconsistencies in data
    - Missing Values
    - Duplicates
    - Errors
    - Outliers
- Removal or replacement
- 
- Every dataset has its identity:
    - Data Distribution - how is the data spread about - what is the std deviation, variance
    - Central Tendencies
        - where the centre of the data is located
        - mean median mode --- represent the centre of the data
    - Data Transformations: (Feature Scaling is one of the things we do here)
        - [Standardization vs Normalization](https://www.geeksforgeeks.org/machine-learning/normalization-vs-standardization/)
        - Normalization - Adjust values to a common scale
            - min max scaling
            - entire data squished between 0 and 1
            - This scales the range to [0, 1] or sometimes [-1, 1]
        - Standardization - Convert data to a standard form for a common scale
            - mean 0 and std deviation 1
            - 

- Feature Scaling - take a feature/column and transform it entirely

In [98]:
import numpy as np
import pandas as pd

data = {
    'ID': [x + 100 for x in range(1, 22)],
    'Name': ['Morozov', 'Alice Smith', 'Bob Jones', 'Charlie John', 'David Lee', 'Eve Martinez', 'Frank Wright', 'Grace Lee', 'Hank Brown', 'Ivy Thompson', 'Jack Davis', 'Athalia', 'Amanda', 'Jacquelina', 'Raphael', 'Rosa Linda', 'Rafeeqa', 'Ameena', 'Raisyaa', 'Hayfa', 'Raisyaa'],
    'Email': ['morosechild@mail', 'alicesmith@mail', None, 'charlie@mail', 'davlee@mail', 'evemartin@mail', 'frank@mail', 'ggrace@mail', None, 'ivytom@mail', 'dav_jac@mail', 'athalia@mail', 'aman_da@mail', 'jac_q@mail', 'Ralph_ael@mail', None, 'feeqa_raff@mail', 'meena@mail', 'syaa_raai@mail', 'hayfa@mail', 'syaa_raai@mail'],
    'Product': ['Camera', None, 'Pc', 'Console', 'Keyboard', 'Pc', 'Keyboard', 'Mouse', 'Cd', 'Pc', 'Headphone', 'Keyboard', None, 'Mouse', 'Pc', 'Smartwatch', 'Tablet', 'Pc', 'Mouse', 'Headphone', 'Mouse'],
    'Quantity': [-3, 1, 1, 1, 1, 1, 2, 1, None, 1, 3, None, 1, 1, 2, 1, None, 1, -2, 2, -2],
    'Price': [41010.99, 987.09, 505.65, 30000.00, 187.90, 199.99, None, 57.00, 90.00, 900.89, 503.77, None, 209.00, 244.56, 99.08, 800.00, 1000.00, 676.00, 761.00, 97.00, 761.00],
    'Delivery': [True, True, True, True, False, True, False, True, True, False, True, False, False, False, False, False, True, True, True, True, True],
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '04/01/2023', '2023-01-06', '2023-01-07', '9th Jan 2024', '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12', '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16', '2023-01-17', '2023-01-18', '20/01/2023', '2023-01-20', '20/01/2023']
}

df = pd.DataFrame(data)
display(df)
df.info()

,ID,Name,Email,Product,Quantity,Price,Delivery,Date
0,101,Morozov,morosechild@mail,Camera,-3.0,41010.99,True,2023-01-01
1,102,Alice Smith,alicesmith@mail,NaN,1.0,987.09,True,2023-01-02
2,103,Bob Jones,NaN,Pc,1.0,505.65,True,2023-01-03
3,104,Charlie John,charlie@mail,Console,1.0,30000.00,True,2023-01-04
4,105,David Lee,davlee@mail,Keyboard,1.0,187.90,False,04/01/2023
5,106,Eve Martinez,evemartin@mail,Pc,1.0,199.99,True,2023-01-06
6,107,Frank Wright,frank@mail,Keyboard,2.0,NaN,False,2023-01-07
7,108,Grace Lee,ggrace@mail,Mouse,1.0,57.00,True,9th Jan 2024
8,109,Hank Brown,NaN,Cd,NaN,90.00,True,2023-01-09
9,110,Ivy Thompson,ivytom@mail,Pc,1.0,900.89,False,2023-01-10
10,111,Jack Davis,dav_jac@mail,Headphone,3.0,503.77,True,2023-01-11
11,112,Athalia,athalia@mail,Keyboard,NaN,NaN,False,2023-01-12
12,113,Amanda,aman_da@mail,NaN,1.0,209.00,False,2023-01-13
13,114,Jacquelina,jac_q@mail,Mouse,1.0,244.56,False,2023-01-14
14,115,Raphael,Ralph_ael@mail,Pc,2.0,99.08,False,2023-01-15
15,116,Rosa Linda,NaN,Smartwatch,1.0,800.00,False,2023-01-16
16,117,Rafeeqa,feeqa_raff@mail,Tablet,NaN,1000.00,True,2023-01-17
17,118,Ameena,meena@mail,Pc,1.0,676.00,True,2023-01-18
18,119,Raisyaa,syaa_raai@mail,Mouse,-2.0,761.00,True,20/01/2023
19,120,Hayfa,hayfa@mail,Headphone,2.0,97.00,True,2023-01-20
20,121,Raisyaa,syaa_raai@mail,Mouse,-2.0,761.00,True,20/01/2023

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        21 non-null     int64
 1   Name      21 non-null     str
 2   Email     18 non-null     str
 3   Product   19 non-null     str
 4   Quantity  18 non-null     float64
 5   Price     19 non-null     float64
 6   Delivery  21 non-null     bool
 7   Date      21 non-null     str
dtypes: bool(1), float64(2), int64(1), str(4)
memory usage: 1.3 KB

In [99]:
display(df.isna().sum())
display(df.isnull().sum())

ID          0
Name        0
Email       3
Product     2
Quantity    3
Price       2
Delivery    0
Date        0
dtype: int64

ID          0
Name        0
Email       3
Product     2
Quantity    3
Price       2
Delivery    0
Date        0
dtype: int64

In [100]:
df.loc[20, 'ID'] = 119
df.duplicated().sum()

np.int64(1)

### Handling Missing Values
- Deletion (Removal of these missing values)
    - Listwise:
        - Rows where any data is missing
    - Pairwise:
        - remove specific fields with missing values, keep the rest
- Imputation (filling in missing values)
    - estimate/calculate/predict values that should have been there
    - should not affect identity of dataset too drastically
    - distribution, central tendencies should remain almost intact
    - Types:
        - Mean/median/mode imputation - put these values in missing places
        - Predictive imputation - using ML we predict missing values first
        - Forward/Backward fill - propagate the values - fill in with the previous or the next one

In [101]:
df_listwised = df.dropna()
display(df_listwised)
display(df_listwised.isna().sum())
df_listwised.info()

,ID,Name,Email,Product,Quantity,Price,Delivery,Date
0,101,Morozov,morosechild@mail,Camera,-3.0,41010.99,True,2023-01-01
3,104,Charlie John,charlie@mail,Console,1.0,30000.00,True,2023-01-04
4,105,David Lee,davlee@mail,Keyboard,1.0,187.90,False,04/01/2023
5,106,Eve Martinez,evemartin@mail,Pc,1.0,199.99,True,2023-01-06
7,108,Grace Lee,ggrace@mail,Mouse,1.0,57.00,True,9th Jan 2024
9,110,Ivy Thompson,ivytom@mail,Pc,1.0,900.89,False,2023-01-10
10,111,Jack Davis,dav_jac@mail,Headphone,3.0,503.77,True,2023-01-11
13,114,Jacquelina,jac_q@mail,Mouse,1.0,244.56,False,2023-01-14
14,115,Raphael,Ralph_ael@mail,Pc,2.0,99.08,False,2023-01-15
17,118,Ameena,meena@mail,Pc,1.0,676.00,True,2023-01-18
18,119,Raisyaa,syaa_raai@mail,Mouse,-2.0,761.00,True,20/01/2023
19,120,Hayfa,hayfa@mail,Headphone,2.0,97.00,True,2023-01-20
20,119,Raisyaa,syaa_raai@mail,Mouse,-2.0,761.00,True,20/01/2023

ID          0
Name        0
Email       0
Product     0
Quantity    0
Price       0
Delivery    0
Date        0
dtype: int64

<class 'pandas.DataFrame'>
Index: 13 entries, 0 to 20
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        13 non-null     int64
 1   Name      13 non-null     str
 2   Email     13 non-null     str
 3   Product   13 non-null     str
 4   Quantity  13 non-null     float64
 5   Price     13 non-null     float64
 6   Delivery  13 non-null     bool
 7   Date      13 non-null     str
dtypes: bool(1), float64(2), int64(1), str(4)
memory usage: 845.0 bytes

In [102]:
df_pairwised = df.dropna(subset= 'Product')
display(df_pairwised)
display(df_pairwised.isnull().sum())
df_pairwised.info()

,ID,Name,Email,Product,Quantity,Price,Delivery,Date
0,101,Morozov,morosechild@mail,Camera,-3.0,41010.99,True,2023-01-01
2,103,Bob Jones,NaN,Pc,1.0,505.65,True,2023-01-03
3,104,Charlie John,charlie@mail,Console,1.0,30000.00,True,2023-01-04
4,105,David Lee,davlee@mail,Keyboard,1.0,187.90,False,04/01/2023
5,106,Eve Martinez,evemartin@mail,Pc,1.0,199.99,True,2023-01-06
6,107,Frank Wright,frank@mail,Keyboard,2.0,NaN,False,2023-01-07
7,108,Grace Lee,ggrace@mail,Mouse,1.0,57.00,True,9th Jan 2024
8,109,Hank Brown,NaN,Cd,NaN,90.00,True,2023-01-09
9,110,Ivy Thompson,ivytom@mail,Pc,1.0,900.89,False,2023-01-10
10,111,Jack Davis,dav_jac@mail,Headphone,3.0,503.77,True,2023-01-11
11,112,Athalia,athalia@mail,Keyboard,NaN,NaN,False,2023-01-12
13,114,Jacquelina,jac_q@mail,Mouse,1.0,244.56,False,2023-01-14
14,115,Raphael,Ralph_ael@mail,Pc,2.0,99.08,False,2023-01-15
15,116,Rosa Linda,NaN,Smartwatch,1.0,800.00,False,2023-01-16
16,117,Rafeeqa,feeqa_raff@mail,Tablet,NaN,1000.00,True,2023-01-17
17,118,Ameena,meena@mail,Pc,1.0,676.00,True,2023-01-18
18,119,Raisyaa,syaa_raai@mail,Mouse,-2.0,761.00,True,20/01/2023
19,120,Hayfa,hayfa@mail,Headphone,2.0,97.00,True,2023-01-20
20,119,Raisyaa,syaa_raai@mail,Mouse,-2.0,761.00,True,20/01/2023

ID          0
Name        0
Email       3
Product     0
Quantity    3
Price       2
Delivery    0
Date        0
dtype: int64

<class 'pandas.DataFrame'>
Index: 19 entries, 0 to 20
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        19 non-null     int64
 1   Name      19 non-null     str
 2   Email     16 non-null     str
 3   Product   19 non-null     str
 4   Quantity  16 non-null     float64
 5   Price     17 non-null     float64
 6   Delivery  19 non-null     bool
 7   Date      19 non-null     str
dtypes: bool(1), float64(2), int64(1), str(4)
memory usage: 1.2 KB

In [103]:
df2 = df.dropna(subset= 'Product').reset_index()
df2.Quantity = abs(df2.Quantity)
display(df2)
display(df2.info())
display(df2.isna().sum())

,index,ID,Name,Email,Product,Quantity,Price,Delivery,Date
0,0,101,Morozov,morosechild@mail,Camera,3.0,41010.99,True,2023-01-01
1,2,103,Bob Jones,NaN,Pc,1.0,505.65,True,2023-01-03
2,3,104,Charlie John,charlie@mail,Console,1.0,30000.00,True,2023-01-04
3,4,105,David Lee,davlee@mail,Keyboard,1.0,187.90,False,04/01/2023
4,5,106,Eve Martinez,evemartin@mail,Pc,1.0,199.99,True,2023-01-06
5,6,107,Frank Wright,frank@mail,Keyboard,2.0,NaN,False,2023-01-07
6,7,108,Grace Lee,ggrace@mail,Mouse,1.0,57.00,True,9th Jan 2024
7,8,109,Hank Brown,NaN,Cd,NaN,90.00,True,2023-01-09
8,9,110,Ivy Thompson,ivytom@mail,Pc,1.0,900.89,False,2023-01-10
9,10,111,Jack Davis,dav_jac@mail,Headphone,3.0,503.77,True,2023-01-11
10,11,112,Athalia,athalia@mail,Keyboard,NaN,NaN,False,2023-01-12
11,13,114,Jacquelina,jac_q@mail,Mouse,1.0,244.56,False,2023-01-14
12,14,115,Raphael,Ralph_ael@mail,Pc,2.0,99.08,False,2023-01-15
13,15,116,Rosa Linda,NaN,Smartwatch,1.0,800.00,False,2023-01-16
14,16,117,Rafeeqa,feeqa_raff@mail,Tablet,NaN,1000.00,True,2023-01-17
15,17,118,Ameena,meena@mail,Pc,1.0,676.00,True,2023-01-18
16,18,119,Raisyaa,syaa_raai@mail,Mouse,2.0,761.00,True,20/01/2023
17,19,120,Hayfa,hayfa@mail,Headphone,2.0,97.00,True,2023-01-20
18,20,119,Raisyaa,syaa_raai@mail,Mouse,2.0,761.00,True,20/01/2023

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     19 non-null     int64
 1   ID        19 non-null     int64
 2   Name      19 non-null     str
 3   Email     16 non-null     str
 4   Product   19 non-null     str
 5   Quantity  16 non-null     float64
 6   Price     17 non-null     float64
 7   Delivery  19 non-null     bool
 8   Date      19 non-null     str
dtypes: bool(1), float64(2), int64(2), str(4)
memory usage: 1.3 KB

None

index       0
ID          0
Name        0
Email       3
Product     0
Quantity    3
Price       2
Delivery    0
Date        0
dtype: int64

In [104]:
df2.Quantity.mean() # NOT VALID FOR IMPUTATION

np.float64(1.5625)

In [105]:
df2.Quantity = df2.Quantity.fillna(df2.Quantity.mode()[0])
display(df2)
df2.isna().sum()

,index,ID,Name,Email,Product,Quantity,Price,Delivery,Date
0,0,101,Morozov,morosechild@mail,Camera,3.0,41010.99,True,2023-01-01
1,2,103,Bob Jones,NaN,Pc,1.0,505.65,True,2023-01-03
2,3,104,Charlie John,charlie@mail,Console,1.0,30000.00,True,2023-01-04
3,4,105,David Lee,davlee@mail,Keyboard,1.0,187.90,False,04/01/2023
4,5,106,Eve Martinez,evemartin@mail,Pc,1.0,199.99,True,2023-01-06
5,6,107,Frank Wright,frank@mail,Keyboard,2.0,NaN,False,2023-01-07
6,7,108,Grace Lee,ggrace@mail,Mouse,1.0,57.00,True,9th Jan 2024
7,8,109,Hank Brown,NaN,Cd,1.0,90.00,True,2023-01-09
8,9,110,Ivy Thompson,ivytom@mail,Pc,1.0,900.89,False,2023-01-10
9,10,111,Jack Davis,dav_jac@mail,Headphone,3.0,503.77,True,2023-01-11
10,11,112,Athalia,athalia@mail,Keyboard,1.0,NaN,False,2023-01-12
11,13,114,Jacquelina,jac_q@mail,Mouse,1.0,244.56,False,2023-01-14
12,14,115,Raphael,Ralph_ael@mail,Pc,2.0,99.08,False,2023-01-15
13,15,116,Rosa Linda,NaN,Smartwatch,1.0,800.00,False,2023-01-16
14,16,117,Rafeeqa,feeqa_raff@mail,Tablet,1.0,1000.00,True,2023-01-17
15,17,118,Ameena,meena@mail,Pc,1.0,676.00,True,2023-01-18
16,18,119,Raisyaa,syaa_raai@mail,Mouse,2.0,761.00,True,20/01/2023
17,19,120,Hayfa,hayfa@mail,Headphone,2.0,97.00,True,2023-01-20
18,20,119,Raisyaa,syaa_raai@mail,Mouse,2.0,761.00,True,20/01/2023

index       0
ID          0
Name        0
Email       3
Product     0
Quantity    0
Price       2
Delivery    0
Date        0
dtype: int64

In [106]:
df2.Email = df2.Email.fillna(df2['Name'].str.lower().str.replace(' ', '_') + '@mail')
display(df2)
df2.info()

,index,ID,Name,Email,Product,Quantity,Price,Delivery,Date
0,0,101,Morozov,morosechild@mail,Camera,3.0,41010.99,True,2023-01-01
1,2,103,Bob Jones,bob_jones@mail,Pc,1.0,505.65,True,2023-01-03
2,3,104,Charlie John,charlie@mail,Console,1.0,30000.00,True,2023-01-04
3,4,105,David Lee,davlee@mail,Keyboard,1.0,187.90,False,04/01/2023
4,5,106,Eve Martinez,evemartin@mail,Pc,1.0,199.99,True,2023-01-06
5,6,107,Frank Wright,frank@mail,Keyboard,2.0,NaN,False,2023-01-07
6,7,108,Grace Lee,ggrace@mail,Mouse,1.0,57.00,True,9th Jan 2024
7,8,109,Hank Brown,hank_brown@mail,Cd,1.0,90.00,True,2023-01-09
8,9,110,Ivy Thompson,ivytom@mail,Pc,1.0,900.89,False,2023-01-10
9,10,111,Jack Davis,dav_jac@mail,Headphone,3.0,503.77,True,2023-01-11
10,11,112,Athalia,athalia@mail,Keyboard,1.0,NaN,False,2023-01-12
11,13,114,Jacquelina,jac_q@mail,Mouse,1.0,244.56,False,2023-01-14
12,14,115,Raphael,Ralph_ael@mail,Pc,2.0,99.08,False,2023-01-15
13,15,116,Rosa Linda,rosa_linda@mail,Smartwatch,1.0,800.00,False,2023-01-16
14,16,117,Rafeeqa,feeqa_raff@mail,Tablet,1.0,1000.00,True,2023-01-17
15,17,118,Ameena,meena@mail,Pc,1.0,676.00,True,2023-01-18
16,18,119,Raisyaa,syaa_raai@mail,Mouse,2.0,761.00,True,20/01/2023
17,19,120,Hayfa,hayfa@mail,Headphone,2.0,97.00,True,2023-01-20
18,20,119,Raisyaa,syaa_raai@mail,Mouse,2.0,761.00,True,20/01/2023

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     19 non-null     int64
 1   ID        19 non-null     int64
 2   Name      19 non-null     str
 3   Email     19 non-null     str
 4   Product   19 non-null     str
 5   Quantity  19 non-null     float64
 6   Price     17 non-null     float64
 7   Delivery  19 non-null     bool
 8   Date      19 non-null     str
dtypes: bool(1), float64(2), int64(2), str(4)
memory usage: 1.3 KB

In [109]:
df2.Price = df2.Price.fillna(df2.Price.mean().round(2))
display(df2)
df2.info()

,index,ID,Name,Email,Product,Quantity,Price,Delivery,Date
0,0,101,Morozov,morosechild@mail,Camera,3.0,41010.99,True,2023-01-01
1,2,103,Bob Jones,bob_jones@mail,Pc,1.0,505.65,True,2023-01-03
2,3,104,Charlie John,charlie@mail,Console,1.0,30000.00,True,2023-01-04
3,4,105,David Lee,davlee@mail,Keyboard,1.0,187.90,False,04/01/2023
4,5,106,Eve Martinez,evemartin@mail,Pc,1.0,199.99,True,2023-01-06
5,6,107,Frank Wright,frank@mail,Keyboard,2.0,4582.00,False,2023-01-07
6,7,108,Grace Lee,ggrace@mail,Mouse,1.0,57.00,True,9th Jan 2024
7,8,109,Hank Brown,hank_brown@mail,Cd,1.0,90.00,True,2023-01-09
8,9,110,Ivy Thompson,ivytom@mail,Pc,1.0,900.89,False,2023-01-10
9,10,111,Jack Davis,dav_jac@mail,Headphone,3.0,503.77,True,2023-01-11
10,11,112,Athalia,athalia@mail,Keyboard,1.0,4582.00,False,2023-01-12
11,13,114,Jacquelina,jac_q@mail,Mouse,1.0,244.56,False,2023-01-14
12,14,115,Raphael,Ralph_ael@mail,Pc,2.0,99.08,False,2023-01-15
13,15,116,Rosa Linda,rosa_linda@mail,Smartwatch,1.0,800.00,False,2023-01-16
14,16,117,Rafeeqa,feeqa_raff@mail,Tablet,1.0,1000.00,True,2023-01-17
15,17,118,Ameena,meena@mail,Pc,1.0,676.00,True,2023-01-18
16,18,119,Raisyaa,syaa_raai@mail,Mouse,2.0,761.00,True,20/01/2023
17,19,120,Hayfa,hayfa@mail,Headphone,2.0,97.00,True,2023-01-20
18,20,119,Raisyaa,syaa_raai@mail,Mouse,2.0,761.00,True,20/01/2023

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     19 non-null     int64
 1   ID        19 non-null     int64
 2   Name      19 non-null     str
 3   Email     19 non-null     str
 4   Product   19 non-null     str
 5   Quantity  19 non-null     float64
 6   Price     19 non-null     float64
 7   Delivery  19 non-null     bool
 8   Date      19 non-null     str
dtypes: bool(1), float64(2), int64(2), str(4)
memory usage: 1.3 KB